create table blocks
(
    numID           varchar(5)   null,
    name            varchar(25)  null,
    textID          varchar(32)  null,
    stackSize       int          null,
    craftability    tinyint(1)   null,
    tool            varchar(3)   null,
    hardness        float        null,
    blastResistance float        null,
    transparent     tinyint(1)   null,
    flammability    tinyint(1)   null,
    fuel            tinyint(1)   null,
    renewability    tinyint(1)   null,
    description     varchar(128) null,
    rarity          varchar(2)   null,
    constraint blocks_ibfk_1
        foreign key (tool) references blocktools (toolID),
    constraint blocks_ibfk_2
        foreign key (rarity) references rarity (rarityID)
);

create index rarity
    on blocks (rarity);

create index tool
    on blocks (tool);

INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('1', 'Stone', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('2', 'Grass', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('3', 'Dirt', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('4', 'Cobblestone', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('5', 'Wooden Plank', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('6', 'Sapling', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('6:1', 'Sapling (Pine)', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('6:2', 'Sapling (Birch)', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('7', 'Bedrock', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('8', 'Water (No Spread)', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('9', 'Water', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('10', 'Lava (No Spread)', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('11', 'Lava', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('12', 'Sand', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('13', 'Gravel', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('14', 'Gold Ore', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('15', 'Iron Ore', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('16', 'Coal Ore', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('17', 'Wood', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('17:1', 'Wood (Pine)', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('17:2', 'Wood (Birch)', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('18', 'Leaves', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('18:1', 'Leaves (Pine)', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('18:2', 'Leaves (Birch)', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('19', 'Sponge', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('20', 'Glass', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('21', 'Lapis Lazuli Ore', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('22', 'Lapis Lazuli Block', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('23', 'Dispenser', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('24', 'Sandstone', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('25', 'Note Block', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('26', 'Bed (Block)', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('27', 'Powered Rail', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('28', 'Detector Rail', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('29', 'Sticky Piston', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('30', 'Web', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('31', 'Tall Grass (Dead Shrub)', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('31:1', 'Tall Grass', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('31:2', 'Tall Grass (Fern)', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('32', 'Dead Shrub', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('33', 'Piston', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('34', 'Piston (Head)', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('35', 'Wool', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('35:1', 'Orange Wool', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('35:2', 'Magenta Wool', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('35:3', 'Light Blue Wool', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('35:4', 'Yellow Wool', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('35:5', 'Lime Wool', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('35:6', 'Pink Wool', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('35:7', 'Gray Wool', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('35:8', 'Light Gray Wool', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('35:9', 'Cyan Wool', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('35:10', 'Purple Wool', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('35:11', 'Blue Wool', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('35:12', 'Brown Wool', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('35:13', 'Green Wool', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('35:14', 'Red Wool', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('35:15', 'Black Wool', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('37', 'Dandelion', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('38', 'Rose', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('39', 'Brown Mushroom', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('40', 'Red Mushroom', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('41', 'Block of Gold', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('42', 'Block of Iron', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('43', 'Stone Slab (Double)', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('43:1', 'Sandstone Slab (Double)', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('43:2', 'Wooden Slab (Double)', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('43:3', 'Cobblestone Slab (Double)', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('43:4', 'Brick Slab (Double)', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('43:5', 'Stone Brick Slab (Double)', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('44', 'Stone Slab', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('44:1', 'Sandstone Slab', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('44:2', 'Wooden Slab', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('44:3', 'Cobblestone Slab', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('44:4', 'Brick Slab', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('44:5', 'Stone Brick Slab', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('45', 'Brick', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('46', 'TNT', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('47', 'Bookcase', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('48', 'Moss Stone', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('49', 'Obsidian', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('50', 'Torch', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('51', 'Fire', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('52', 'Mob Spawner', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('53', 'Wooden Stairs', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('54', 'Chest', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('55', 'Redstone Wire', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('56', 'Diamond Ore', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('57', 'Block of Diamond', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('58', 'Workbench', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('59', 'Wheat', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('60', 'Farmland', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('61', 'Furnace', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('62', 'Furnace', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('63', 'Sign', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('64', 'Wood Door', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('65', 'Ladder', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('66', 'Rails', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('67', 'Cobblestone Stairs', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('68', 'Sign', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('69', 'Lever', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('70', 'Stone Pressure Plate', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('71', 'Iron Door', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('72', 'Wooden Pressure Plate', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('73', 'Redstone Ore', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('74', 'Redstone Ore', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('75', 'Redstone Torch', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('76', 'Redstone Torch', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('77', 'Stone Button', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('78', 'Snow', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('79', 'Ice', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('80', 'Snow Block', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('81', 'Cactus', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('82', 'Clay Block', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('83', 'Sugar Cane', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('84', 'Jukebox', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('85', 'Fence', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('86', 'Pumpkin', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('87', 'Netherrack', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('88', 'Soul Sand', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('89', 'Glowstone', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('90', 'Portal', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('91', 'Jack-O-Lantern', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('92', 'Cake', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('93', 'Redstone Repeater', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('94', 'Redstone Repeater', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('95', 'Locked Chest', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('96', 'Trapdoor', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('97', 'Silverfish Stone', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('98', 'Stone Bricks', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('98:1', 'Mossy Stone Bricks', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('98:2', 'Cracked Stone Bricks', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('99', 'Brown Mushroom', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('100', 'Red Mushroom', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('101', 'Iron Bars', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('102', 'Glass Pane', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('103', 'Melon', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('104', 'Pumpkin Vine', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('105', 'Melon Vine', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('106', 'Vines', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('107', 'Fence Gate', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('108', 'Brick Stairs', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('109', 'Stone Brick Stairs', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('110', 'Mycelium', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('111', 'Lily Pad', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('112', 'Nether Brick', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('113', 'Nether Brick Fence', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('114', 'Nether Brick Stairs', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('115', 'Nether Wart', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('116', 'Enchantment Table', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('117', 'Brewing Stand', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('118', 'Cauldron', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('119', 'End Portal', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('120', 'End Portal Frame', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('121', 'End Stone', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('122', 'Dragon Egg', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('321', 'Painting', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('323', 'Sign', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('324', 'Wooden Door', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('336', 'Clay Brick', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('330', 'Iron Door', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('338', 'Sugar Cane', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('355', 'Bed', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('356', 'Redstone Repeater', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('374', 'Glass Bottle', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('375', 'Spider Eye', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('376', 'Fermented Spider Eye', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('377', 'Blaze Powder', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('378', 'Magma Cream', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('379', 'Brewing Stand', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('380', 'Cauldron', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('381', 'Eye of Ender', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('382', 'Glistering Melon', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('2256', 'Music Disk', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('2257', 'Music Disk', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('2258', 'Music Disk', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('2259', 'Music Disk', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('2260', 'Music Disk', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('2261', 'Music Disk', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('2262', 'Music Disk', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('2263', 'Music Disk', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('2264', 'Music Disk', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('2265', 'Music Disk', null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, tool, hardness, blastResistance, transparent, flammability, fuel, renewability, description, rarity) VALUES ('2266', 'Music Disk', null, null, null, null, null, null, null, null, null, null, null, null);
