create table blocks
(
    numID           varchar(5)   not null
        primary key,
    name            varchar(32)  null,
    textID          varchar(64)  null,
    stackSize       int          null,
    craftability    tinyint(1)   null,
    hardness        float        null,
    blastResistance float        null,
    transparency    tinyint(1)   null,
    flammability    tinyint(1)   null,
    fuel            tinyint(1)   null,
    renewability    tinyint(1)   null,
    description     varchar(128) null,
    rarityID        varchar(2)   null,
    constraint blocks_ibfk_2
        foreign key (rarityID) references rarity (rarityID)
);

create index rarity
    on blocks (rarityID);

INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('1', 'Stone', 'minecraft:stone', 64, 0, 1.5, 30, 0, 0, 0, 0, 'Basic solid block found underground, used in construction.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('10', 'Lava (No Spread)', 'minecraft:lava', 1, 0, 100, 500, 1, 0, 0, 0, 'Lava block without spreading behavior.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('100', 'Red Mushroom (Block)', 'minecraft:red_mushroom_block', 64, 0, 0.2, 1, 0, 1, 0, 1, 'Large red mushroom cap block with white dots.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('101', 'Iron Bars', 'minecraft:iron_bars', 64, 0, 0.2, 5, 0, 0, 0, 0, 'Iron bars, decorative and functional bars for fencing.', '3');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('102', 'Glass Pane', 'minecraft:glass_pane', 64, 1, 0.3, 0.3, 1, 0, 0, 0, 'Glass pane, thin transparent block used for windows.', '3');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('103', 'Melon (Block)', 'minecraft:melon_block', 64, 0, 1, 1, 0, 0, 0, 1, 'Block that drops melon slices when broken.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('104', 'Pumpkin Vine', 'minecraft:pumpkin_stem', 64, 0, 0, 1, 0, 1, 0, 1, 'Pumpkin vine, part of the pumpkin plant that grows.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('105', 'Melon Vine', 'minecraft:melon_stem', 64, 0, 0, 1, 0, 1, 0, 1, 'Melon vine, part of the melon plant that grows.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('106', 'Vines', 'minecraft:vine', 64, 0, 0.2, 0.2, 1, 1, 0, 1, 'Vines, climbable plants growing on blocks.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('107', 'Fence Gate', 'minecraft:oak_fence_gate', 64, 1, 2, 2, 0, 1, 1, 1, 'Fence gate, gate that can open and close in a fence.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('108', 'Brick Stairs', 'minecraft:brick_stairs', 64, 1, 2, 2, 0, 0, 0, 0, 'Brick stairs, stair block made from bricks.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('109', 'Stone Brick Stairs', 'minecraft:stone_brick_stairs', 64, 1, 1.5, 6, 0, 0, 0, 0, 'Stone brick stairs, stair block made from stone bricks.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('11', 'Lava', 'minecraft:lava', 1, 0, 100, 500, 1, 0, 0, 0, 'Molten lava, dangerous liquid that causes fire damage.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('110', 'Mycelium', 'minecraft:mycelium', 64, 0, 0.6, 0.6, 1, 0, 0, 0, 'Mycelium, fungus-covered dirt found in mushroom biomes.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('111', 'Lily Pad', 'minecraft:lily_pad', 64, 0, 0, 0, 1, 0, 0, 1, 'Lily pad, floating plant on water surfaces.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('112', 'Nether Brick', 'minecraft:nether_bricks', 64, 1, 2, 30, 0, 0, 0, 0, 'Nether brick, decorative block found in Nether fortresses.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('113', 'Nether Brick Fence', 'minecraft:nether_brick_fence', 64, 1, 2, 30, 0, 0, 0, 0, 'Nether brick fence, fence made from nether bricks.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('114', 'Nether Brick Stairs', 'minecraft:nether_brick_stairs', 64, 1, 2, 30, 0, 0, 0, 0, 'Nether brick stairs, stairs made from nether bricks.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('115', 'Nether Wart', 'minecraft:nether_wart', 64, 0, 0, 0, 0, 0, 0, 1, 'Nether wart, plant grown in the Nether used for brewing.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('116', 'Enchantment Table', 'minecraft:enchanting_table', 64, 1, 5, 30, 0, 0, 0, 0, 'Enchantment table, block used to enchant items.', '3');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('117', 'Brewing Stand', 'minecraft:brewing_stand', 64, 1, 0.5, 2.5, 1, 0, 0, 1, 'Used to brew potions with water bottles and ingredients.', '3');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('118', 'Cauldron', 'minecraft:cauldron', 64, 1, 2, 15, 1, 0, 0, 1, 'Used to hold water and interact with potions or dyes.', '3');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('119', 'End Portal', 'minecraft:end_portal', 1, 0, -1, -1, 0, 0, 0, 0, 'End portal, gateway to the End dimension.', '4');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('12', 'Sand', 'minecraft:sand', 64, 0, 0.5, 2.5, 0, 0, 0, 0, 'Loose granular block found in deserts and beaches.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('120', 'End Portal Frame', 'minecraft:end_portal_frame', 64, 0, -1, -1, 0, 0, 0, 0, 'End portal frame, frame block used to build End portals.', '4');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('121', 'End Stone', 'minecraft:end_stone', 64, 0, 3, 3, 0, 0, 0, 0, 'End stone, block found in the End dimension.', '3');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('122', 'Dragon Egg', 'minecraft:dragon_egg', 64, 0, 3, 0, 0, 0, 0, 0, 'Dragon egg, unique item dropped by the Ender Dragon.', '4');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('13', 'Gravel', 'minecraft:gravel', 64, 0, 0.6, 3, 0, 0, 0, 0, 'Gravel block, falls if unsupported and drops flint sometimes.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('14', 'Gold Ore', 'minecraft:gold_ore', 64, 0, 3, 15, 0, 0, 0, 0, 'Ore block containing gold, mined for gold nuggets.', '3');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('15', 'Iron Ore', 'minecraft:iron_ore', 64, 0, 3, 15, 0, 0, 0, 0, 'Ore block containing iron, mined for iron ingots.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('16', 'Coal Ore', 'minecraft:coal_ore', 64, 0, 3, 15, 0, 0, 0, 0, 'Ore block containing coal, used as fuel.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('17', 'Wood (Oak)', 'minecraft:oak_wood', 64, 1, 2, 15, 0, 1, 1, 1, 'Oak wood block, used as a basic building material.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('17:1', 'Wood (Spruce)', 'minecraft:spruce_wood', 64, 1, 2, 15, 0, 1, 1, 1, 'Spruce wood block, similar to oak but with a darker texture.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('17:2', 'Wood (Birch)', 'minecraft:birch_wood', 64, 1, 2, 15, 0, 1, 1, 1, 'Birch wood block, a pale-colored alternative to oak with the same properties.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('18', 'Leaves (Oak)', 'minecraft:oak_leaves', 64, 0, 0.2, 1, 1, 1, 0, 1, 'Leaf block from oak trees, decays unless connected to wood.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('18:1', 'Leaves (Pine)', 'minecraft:spruce_leaves', 64, 0, 0.2, 1, 1, 1, 0, 1, 'Spruce (pine) tree leaves block, semi-transparent and flammable, often drops saplings.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('18:2', 'Leaves (Birch)', 'minecraft:birch_leaves', 64, 0, 0.2, 1, 1, 1, 0, 1, 'Birch tree leaves block, light-colored and often used for decoration or sapling drops.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('19', 'Sponge', 'minecraft:sponge', 64, 0, 0.6, 3, 0, 1, 0, 0, 'Sponge block, absorbs water in a radius.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('2', 'Grass (Block)', 'minecraft:grass_block', 64, 0, 0.6, 3, 0, 0, 0, 1, 'Grass-covered dirt block, commonly found on the surface of most biomes.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('20', 'Glass', 'minecraft:glass', 64, 1, 0.3, 1.5, 1, 0, 0, 0, 'Transparent block, used for windows and decoration.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('21', 'Lapis Lazuli Ore', 'minecraft:lapis_ore', 64, 0, 3, 15, 0, 0, 0, 0, 'Ore containing Lapis Lazuli, used for enchanting.', '3');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('22', 'Lapis Lazuli Block', 'minecraft:lapis_block', 64, 1, 3, 30, 0, 0, 0, 0, 'Block made of Lapis Lazuli, used for decoration.', '3');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('23', 'Dispenser', 'minecraft:dispenser', 64, 1, 3.5, 17.5, 0, 0, 0, 1, 'Redstone mechanism block that shoots items.', '3');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('24', 'Sandstone', 'minecraft:sandstone', 64, 1, 0.8, 4, 0, 0, 0, 1, 'Block made of compressed sand, decorative and craftable.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('25', 'Note Block', 'minecraft:note_block', 64, 1, 0.8, 5, 0, 0, 0, 1, 'Block that plays musical notes when activated.', '3');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('26', 'Bed', 'minecraft:bed', 1, 1, 0.2, 1, 1, 1, 0, 1, 'Used by players to sleep and set spawn point.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('27', 'Powered Rail', 'minecraft:powered_rail', 64, 1, 0.7, 7.5, 0, 0, 0, 1, 'Rail block powered by redstone, speeds up minecarts.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('28', 'Detector Rail', 'minecraft:detector_rail', 64, 1, 0.7, 7.5, 0, 0, 0, 1, 'Rail that detects minecart passage and emits a redstone signal.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('29', 'Sticky Piston', 'minecraft:sticky_piston', 64, 1, 0.5, 12.5, 0, 0, 0, 1, 'Piston that can stick to blocks when retracting.', '3');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('3', 'Dirt', 'minecraft:dirt', 64, 0, 0.5, 0.5, 0, 1, 0, 1, 'Dirt block, common and found below grass blocks.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('30', 'Web', 'minecraft:cobweb', 64, 0, 4, 20, 1, 1, 0, 0, 'Cobweb block that slows down entities.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('31', 'Dead Shrub', 'minecraft:dead_bush', 64, 0, 0, 0, 1, 1, 1, 0, 'A small dry shrub found in desert biomes, breaks instantly without drops unless sheared.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('31:1', 'Tall Grass', 'minecraft:tall_grass', 64, 0, 0, 0, 1, 1, 0, 1, 'A decorative grassy plant that grows on grass blocks, drops seeds when broken.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('31:2', 'Fern', 'minecraft:fern', 64, 0, 0, 0, 1, 1, 0, 1, 'A green plant similar to tall grass, found in forest biomes and only collectible with shears.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('321', 'Painting', 'minecraft:painting', 64, 1, 0, 0, 1, 0, 0, 0, 'Painting, decorative item placed on walls.', '4');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('33', 'Piston', 'minecraft:piston', 64, 1, 0.5, 12.5, 0, 0, 0, 1, 'Piston block, pushes blocks when powered.', '3');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('34', 'Piston (Head)', 'minecraft:piston_head', 64, 0, 0.5, 0.5, 0, 0, 0, 0, 'Extended part of a piston when activated.', '3');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('35', 'Wool', 'minecraft:white_wool', 64, 1, 0.8, 0.8, 0, 1, 1, 1, 'Block made from wool, used for decoration and crafting.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('35:1', 'Orange Wool', 'minecraft:orange_wool', 64, 1, 0.8, 0.8, 0, 1, 1, 1, 'Orange dyed wool block.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('35:10', 'Purple Wool', 'minecraft:purple_wool', 64, 1, 0.8, 0.8, 0, 1, 1, 1, 'Purple dyed wool block.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('35:11', 'Blue Wool', 'minecraft:blue_wool', 64, 1, 0.8, 0.8, 0, 1, 1, 1, 'Blue dyed wool block.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('35:12', 'Brown Wool', 'minecraft:brown_wool', 64, 1, 0.8, 0.8, 0, 1, 1, 1, 'Brown dyed wool block.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('35:13', 'Green Wool', 'minecraft:green_wool', 64, 1, 0.8, 0.8, 0, 1, 1, 1, 'Green dyed wool block.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('35:14', 'Red Wool', 'minecraft:red_wool', 64, 1, 0.8, 0.8, 0, 1, 1, 1, 'Red dyed wool block.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('35:15', 'Black Wool', 'minecraft:black_wool', 64, 1, 0.8, 0.8, 0, 1, 1, 1, 'Black dyed wool block.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('35:2', 'Magenta Wool', 'minecraft:magenta_wool', 64, 1, 0.8, 0.8, 0, 1, 1, 1, 'Magenta dyed wool block.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('35:3', 'Light Blue Wool', 'minecraft:light_blue_wool', 64, 1, 0.8, 0.8, 0, 1, 1, 1, 'Light blue dyed wool block.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('35:4', 'Yellow Wool', 'minecraft:yellow_wool', 64, 1, 0.8, 0.8, 0, 1, 1, 1, 'Yellow dyed wool block.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('35:5', 'Lime Wool', 'minecraft:lime_wool', 64, 1, 0.8, 0.8, 0, 1, 1, 1, 'Lime dyed wool block.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('35:6', 'Pink Wool', 'minecraft:pink_wool', 64, 1, 0.8, 0.8, 0, 1, 1, 1, 'Pink dyed wool block.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('35:7', 'Gray Wool', 'minecraft:gray_wool', 64, 1, 0.8, 0.8, 0, 1, 1, 1, 'Gray dyed wool block.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('35:8', 'Light Gray Wool', 'minecraft:light_gray_wool', 64, 1, 0.8, 0.8, 0, 1, 1, 1, 'Light gray dyed wool block.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('35:9', 'Cyan Wool', 'minecraft:cyan_wool', 64, 1, 0.8, 0.8, 0, 1, 1, 1, 'Cyan dyed wool block.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('37', 'Dandelion', 'minecraft:dandelion', 64, 0, 0, 0, 1, 1, 0, 1, 'Yellow flower, decorative and used in crafting dyes.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('38', 'Rose', 'minecraft:poppy', 64, 0, 0, 0, 1, 1, 0, 1, 'Red rose flower, decorative and used for crafting.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('39', 'Brown Mushroom', 'minecraft:brown_mushroom', 64, 0, 0, 0.5, 1, 0, 0, 1, 'Brown mushroom block, grows in dark areas.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('4', 'Cobblestone', 'minecraft:cobblestone', 64, 0, 2, 30, 0, 0, 0, 1, 'Rough stone block obtained by mining stone.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('40', 'Red Mushroom', 'minecraft:red_mushroom', 64, 0, 0, 0.5, 1, 0, 0, 1, 'Red mushroom block, grows in dark areas.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('41', 'Block of Gold', 'minecraft:gold_block', 64, 1, 3, 30, 0, 0, 0, 0, 'Block made of solid gold.', '3');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('42', 'Block of Iron', 'minecraft:iron_block', 64, 1, 5, 30, 0, 0, 0, 0, 'Block made of solid iron.', '3');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('43', 'Stone Slab (Double)', 'minecraft:double_stone_slab', 64, 1, 2, 2, 0, 0, 0, 1, 'Double stone slab, crafted by combining two stone slabs.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('43:1', 'Sandstone Slab (Double)', 'minecraft:double_sandstone_slab', 64, 1, 2, 2, 0, 0, 0, 1, 'Double sandstone slab.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('43:2', 'Wooden Slab (Double)', 'minecraft:double_wooden_slab', 64, 1, 2, 2, 0, 1, 1, 1, 'Double wooden slab.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('43:3', 'Cobblestone Slab (Double)', 'minecraft:double_cobblestone_slab', 64, 1, 2, 2, 0, 0, 0, 1, 'Double cobblestone slab.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('43:4', 'Brick Slab (Double)', 'minecraft:double_brick_slab', 64, 1, 2, 2, 0, 0, 0, 1, 'Double brick slab.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('43:5', 'Stone Brick Slab (Double)', 'minecraft:double_stone_brick_slab', 64, 1, 2, 2, 0, 0, 0, 1, 'Double stone brick slab.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('44', 'Stone Slab', 'minecraft:stone_slab', 64, 1, 2, 2, 0, 0, 0, 1, 'Single stone slab, used for building and decoration.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('44:1', 'Sandstone Slab', 'minecraft:sandstone_slab', 64, 1, 2, 2, 0, 0, 0, 1, 'Single sandstone slab block.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('44:2', 'Wooden Slab', 'minecraft:wooden_slab', 64, 1, 2, 2, 0, 1, 1, 1, 'Single wooden slab block.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('44:3', 'Cobblestone Slab', 'minecraft:cobblestone_slab', 64, 1, 2, 2, 0, 0, 0, 1, 'Single cobblestone slab block.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('44:4', 'Brick Slab', 'minecraft:brick_slab', 64, 1, 2, 2, 0, 0, 0, 1, 'Single brick slab block.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('44:5', 'Stone Brick Slab', 'minecraft:stone_brick_slab', 64, 1, 2, 2, 0, 0, 0, 1, 'Single stone brick slab block.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('45', 'Brick', 'minecraft:bricks', 64, 1, 2, 6, 0, 0, 0, 1, 'Block made from bricks, commonly used in building.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('46', 'TNT', 'minecraft:tnt', 64, 1, 0, 4, 0, 0, 0, 1, 'Explosive TNT block, ignites and explodes after delay.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('47', 'Bookcase', 'minecraft:bookshelf', 64, 1, 1.5, 1.5, 0, 0, 0, 1, 'Bookcase block, decorative and used to enhance enchantment tables.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('48', 'Moss Stone', 'minecraft:mossy_cobblestone', 64, 0, 2, 6, 0, 0, 0, 0, 'Moss stone, stone covered with moss, decorative block.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('49', 'Obsidian', 'minecraft:obsidian', 64, 0, 50, 1200, 0, 0, 0, 0, 'Obsidian, very hard block formed by water meeting lava.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('5', 'Wooden Plank', 'minecraft:oak_planks', 64, 1, 2, 15, 0, 1, 1, 1, 'Crafted from wood logs, used for building and crafting.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('50', 'Torch', 'minecraft:torch', 64, 1, 0, 0, 1, 0, 0, 0, 'Torch block, provides light source.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('51', 'Fire', 'minecraft:fire', 64, 0, 0, 0, 1, 0, 0, 1, 'Fire block, spreads and damages entities.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('52', 'Mob Spawner', 'minecraft:spawner', 64, 0, 5, 0, 0, 0, 0, 0, 'Mob spawner block, generates mobs when activated.', '4');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('53', 'Wooden Stairs', 'minecraft:oak_stairs', 64, 1, 2, 2, 0, 1, 1, 1, 'Wooden stairs block, used to create staircases.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('54', 'Chest', 'minecraft:chest', 64, 1, 2.5, 2.5, 0, 0, 0, 1, 'Chest block, used for item storage.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('55', 'Redstone Wire', 'minecraft:redstone_wire', 64, 0, 0, 0, 1, 0, 0, 1, 'Redstone wire, transmits redstone signals.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('56', 'Diamond Ore', 'minecraft:diamond_ore', 64, 0, 3, 3, 0, 0, 0, 0, 'Diamond ore block, source of diamonds.', '3');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('57', 'Block of Diamond', 'minecraft:diamond_block', 64, 1, 5, 30, 0, 0, 0, 0, 'Block of diamond, crafted from diamonds.', '3');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('58', 'Workbench', 'minecraft:crafting_table', 64, 1, 2.5, 2.5, 0, 0, 0, 1, 'Workbench (crafting table), used for crafting items.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('59', 'Wheat (Crop)', 'minecraft:wheat', 64, 0, 0, 0, 1, 1, 0, 1, 'Crop grown from seeds, used to craft bread.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('6', 'Sapling (Oak)', 'minecraft:oak_sapling', 64, 0, 0, 0, 1, 1, 1, 1, 'Oak tree sapling, grows into a oak tree.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('6:1', 'Sapling (Spruce)', 'minecraft:spruce_sapling', 64, 0, 0, 0, 1, 1, 1, 1, 'Spruce tree sapling, grows into a spruce tree.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('6:2', 'Sapling (Birch)', 'minecraft:birch_sapling', 64, 0, 0, 0, 1, 1, 1, 1, 'Birch tree sapling, grows into a birch tree.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('60', 'Farmland', 'minecraft:farmland', 64, 0, 0.6, 0.6, 0, 0, 0, 1, 'Farmland block, tilled dirt used for planting crops.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('61', 'Furnace', 'minecraft:furnace', 64, 1, 3.5, 3.5, 0, 0, 0, 1, 'Furnace block, used for smelting and cooking.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('62', 'Furnace (Smelting)', 'minecraft:furnace', 64, 1, 3.5, 17.5, 0, 0, 0, 1, 'Block used to smelt ores and cook food.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('63', 'Sign', 'minecraft:standing_sign', 16, 1, 1, 1, 1, 1, 1, 1, 'Free-standing wooden sign used to display text.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('64', 'Wood Door', 'minecraft:wooden_door', 64, 1, 3, 15, 1, 1, 1, 1, 'Wooden door that can be opened or closed by players or redstone.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('65', 'Ladder', 'minecraft:ladder', 64, 1, 0.4, 2, 0, 1, 0, 1, 'Ladder block, allows climbing vertically.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('66', 'Rails', 'minecraft:rail', 64, 1, 0.7, 0.7, 0, 0, 0, 1, 'Rail block for minecarts to travel on.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('67', 'Cobblestone Stairs', 'minecraft:cobblestone_stairs', 64, 1, 2, 2, 0, 0, 0, 1, 'Cobblestone stairs block, used for building stairs.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('68', 'Sign (Wall Block)', 'minecraft:wall_sign', 16, 1, 1, 1, 1, 1, 1, 1, 'Wall-mounted wooden sign used to display text.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('69', 'Lever', 'minecraft:lever', 64, 1, 0, 0.5, 0, 0, 0, 1, 'Lever block, used as a switch for redstone mechanisms.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('7', 'Bedrock', 'minecraft:bedrock', 64, 0, -1, 18000000, 0, 0, 0, 0, 'Indestructible block that forms the bottom layer of the world.', '4');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('70', 'Stone Pressure Plate', 'minecraft:stone_pressure_plate', 64, 1, 0.5, 0.5, 0, 0, 0, 1, 'Stone pressure plate, activates redstone when stepped on.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('71', 'Iron Door', 'minecraft:iron_door', 64, 1, 5, 5, 0, 0, 0, 1, 'Iron door, stronger door opened by redstone or buttons.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('72', 'Wooden Pressure Plate', 'minecraft:oak_pressure_plate', 64, 1, 0.5, 0.5, 0, 1, 1, 1, 'Wooden pressure plate, activates redstone when stepped on.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('73', 'Redstone Ore', 'minecraft:redstone_ore', 64, 0, 3, 3, 0, 0, 0, 0, 'Redstone ore, emits light and drops redstone when mined.', '3');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('74', 'Redstone Ore (Glowing)', 'minecraft:lit_redstone_ore', 64, 0, 3, 15, 0, 0, 0, 0, 'Glowing variant of redstone ore, emits light when stepped on or clicked.', '3');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('75', 'Redstone Torch (Off)', 'minecraft:unlit_redstone_torch', 64, 1, 0, 0, 1, 1, 0, 1, 'Inactive redstone torch used in circuitry.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('76', 'Redstone Torch', 'minecraft:redstone_torch', 64, 1, 0, 0, 1, 0, 0, 1, 'Redstone torch, provides power for redstone circuits.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('77', 'Stone Button', 'minecraft:stone_button', 64, 1, 0, 0.5, 0, 0, 0, 1, 'Stone button, sends a short redstone signal when pressed.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('78', 'Snow', 'minecraft:snow', 64, 0, 0.1, 0.2, 1, 0, 0, 1, 'Snow layer, thin layer of snow covering blocks.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('79', 'Ice', 'minecraft:ice', 64, 0, 0.5, 0.5, 1, 0, 0, 0, 'Ice block, slippery and melts near light sources.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('8', 'Water (No Spread)', 'minecraft:water', 1, 0, 100, 500, 1, 0, 0, 1, 'Water block without spreading behavior.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('80', 'Snow Block', 'minecraft:snow_block', 64, 1, 0.2, 0.2, 0, 0, 0, 1, 'Snow block, solid block made from snow.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('81', 'Cactus', 'minecraft:cactus', 64, 0, 0.4, 0.4, 1, 0, 0, 1, 'Cactus block, damages entities touching it.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('82', 'Clay Block', 'minecraft:clay', 64, 1, 0.6, 2, 0, 0, 0, 1, 'Clay block, used for crafting bricks and decoration.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('83', 'Sugar Cane (Block)', 'minecraft:reeds', 64, 0, 0, 0, 1, 1, 0, 1, 'Tall, growable plant used to craft sugar and paper.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('84', 'Jukebox', 'minecraft:jukebox', 64, 1, 2, 2, 0, 0, 0, 0, 'Jukebox block, plays music discs.', '3');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('85', 'Fence', 'minecraft:oak_fence', 64, 1, 2, 2, 0, 1, 1, 1, 'Fence block, used to create enclosures.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('86', 'Pumpkin', 'minecraft:pumpkin', 64, 1, 1, 1, 0, 0, 0, 1, 'Pumpkin block, decorative and can be carved or used for golems.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('87', 'Netherrack', 'minecraft:netherrack', 64, 0, 0.4, 2, 0, 0, 0, 0, 'Netherrack, common block in the Nether dimension.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('88', 'Soul Sand', 'minecraft:soul_sand', 64, 0, 0.5, 2.5, 0, 0, 0, 0, 'Soul Sand, slows movement and allows nether wart to grow.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('89', 'Glowstone', 'minecraft:glowstone', 64, 1, 0.3, 1.5, 1, 0, 0, 0, 'Glowstone, emits light, found in the Nether.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('9', 'Water', 'minecraft:water', 1, 0, 100, 500, 1, 0, 0, 1, 'Liquid water block, used in oceans, rivers, and lakes.', '1');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('90', 'Nether Portal', 'minecraft:nether_portal', 1, 0, -1, 18, 0, 0, 0, 0, 'Portal block, used to enter the Nether dimension.', '4');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('91', 'Jack-O-Lantern', 'minecraft:jack_o_lantern', 64, 1, 1, 1, 0, 0, 0, 1, 'Jack-O-Lantern, lit pumpkin that emits light.', '4');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('92', 'Cake (Block)', 'minecraft:cake', 1, 1, 0.5, 2.5, 1, 0, 0, 0, 'Edible block that restores hunger when interacted with.', '4');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('93', 'Redstone Repeater (Block Off)', 'minecraft:unpowered_repeater', 64, 1, 0, 0, 1, 0, 0, 1, 'Inactive redstone repeater used for delaying signals.', '3');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('94', 'Redstone Repeater (Block On)', 'minecraft:powered_repeater', 64, 1, 0, 0, 1, 0, 0, 1, 'Powered redstone repeater emitting signal.', '3');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('95', 'Locked Chest', 'minecraft:locked_chest', 64, 0, 0, 30, 0, 0, 0, 0, 'Locked chest, secure chest that can be locked by players.', '4');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('96', 'Trapdoor', 'minecraft:oak_trapdoor', 64, 1, 3, 0.5, 0, 1, 0, 1, 'Trapdoor, horizontal door that can open and close.', '4');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('97', 'Silverfish Stone', 'minecraft:infested_stone', 64, 0, 3, 30, 0, 0, 0, 0, 'Silverfish stone, stone block hiding a silverfish mob.', '3');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('98', 'Stone Bricks', 'minecraft:stone_bricks', 64, 1, 1.5, 6, 0, 0, 0, 0, 'Stone bricks, decorative variant of stone used in building.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('98:1', 'Mossy Stone Bricks', 'minecraft:mossy_stone_bricks', 64, 0, 1.5, 6, 0, 0, 0, 0, 'Mossy stone bricks, stone bricks covered in moss.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('98:2', 'Cracked Stone Bricks', 'minecraft:cracked_stone_bricks', 64, 0, 1.5, 6, 0, 0, 0, 0, 'Cracked stone bricks, damaged variant of stone bricks.', '2');
INSERT INTO minecraftalpha.blocks (numID, name, textID, stackSize, craftability, hardness, blastResistance, transparency, flammability, fuel, renewability, description, rarityID) VALUES ('99', 'Brown Mushroom (Block)', 'minecraft:brown_mushroom_block', 64, 0, 0.2, 1, 0, 1, 0, 1, 'Large brown mushroom cap block, part of giant fungi.', '1');
