create table items
(
    numID        varchar(6)   null,
    name         varchar(20)  null,
    textID       varchar(50)  null,
    stackSize    int          null,
    craftability tinyint(1)   null,
    renewability tinyint(1)   null,
    description  varchar(128) null,
    rarityID     varchar(2)   null,
    constraint items_ibfk_1
        foreign key (rarityID) references rarity (rarityID)
);

create index rarity
    on items (rarityID);

INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('344', 'Egg', 'minecraft:egg', 16, 0, 1, 'Egg : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('345', 'Compass', 'minecraft:compass', 1, 1, 0, 'Compass : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('346', 'Fishing Rod', 'minecraft:fishing_rod', 64, 0, 1, 'Fishing Rod : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('347', 'Watch', 'minecraft:clock', 1, 1, 0, 'Watch : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('348', 'Glowstone Dust', 'minecraft:glowstone_dust', 64, 0, 0, 'Glowstone Dust : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('351', 'Ink Sack', 'minecraft:black_dye', 64, 1, 1, 'Ink Sack : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('351:1', 'Rose Red Dye', 'minecraft:red_dye', 64, 1, 1, 'Rose Red Dye : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('351:2', 'Cactus Green Dye', 'minecraft:green_dye', 64, 1, 1, 'Cactus Green Dye : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('351:3', 'Coca Bean', 'minecraft:brown_dye', 64, 1, 1, 'Coca Bean : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('351:4', 'Lapis Lazuli', 'minecraft:blue_dye', 64, 1, 1, 'Lapis Lazuli : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('351:5', 'Purple Dye', 'minecraft:purple_dye', 64, 1, 1, 'Purple Dye : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('351:6', 'Cyan Dye', 'minecraft:cyan_dye', 64, 1, 1, 'Cyan Dye : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('351:7', 'Light Gray Dye', 'minecraft:light_gray_dye', 64, 1, 1, 'Light Gray Dye : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('351:8', 'Gray Dye', 'minecraft:gray_dye', 64, 1, 1, 'Gray Dye : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('351:9', 'Pink Dye', 'minecraft:pink_dye', 64, 1, 1, 'Pink Dye : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('351:10', 'Lime Dye', 'minecraft:lime_dye', 64, 1, 1, 'Lime Dye : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('351:11', 'Dandelion Yellow Dye', 'minecraft:yellow_dye', 64, 1, 1, 'Dandelion Yellow Dye : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('351:12', 'Light Blue Dye', 'minecraft:light_blue_dye', 64, 1, 1, 'Light Blue Dye : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('351:13', 'Magenta Dye', 'minecraft:magenta_dye', 64, 1, 1, 'Magenta Dye : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('351:14', 'Orange Dye', 'minecraft:orange_dye', 64, 1, 1, 'Orange Dye : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('351:15', 'Bone Meal', 'minecraft:bone_meal', 64, 1, 1, 'Bone Meal : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('352', 'Bone', 'minecraft:bone', 64, 0, 1, 'Bone : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('353', 'Sugar', 'minecraft:sugar', 64, 1, 1, 'Sugar : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('339', 'Paper', 'minecraft:paper', 64, 1, 1, 'Paper : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('340', 'Book', 'minecraft:book', 64, 1, 1, 'Book : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('341', 'Slime Ball', 'minecraft:slime_ball', 64, 0, 1, 'Slime Ball : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('337', 'Clay', 'minecraft:clay', 64, 0, 0, 'Clay : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('334', 'Leather', 'minecraft:leather', 64, 0, 1, 'Leather : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('332', 'Snowball', 'minecraft:snowball', 16, 0, 1, 'Snowball : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('329', 'Saddle', 'minecraft:saddle', 1, 0, 0, 'Saddle : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('318', 'Flint', 'minecraft:flint', 64, 0, 0, 'Flint : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('296', 'Wheat', 'minecraft:wheat', 64, 1, 1, 'Wheat : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('287', 'String', 'minecraft:string', 64, 0, 1, 'String : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('288', 'Feather', 'minecraft:feather', 64, 0, 1, 'Feather : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('289', 'Gunpowder', 'minecraft:gunpowder', 64, 0, 1, 'Gunpowder : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('280', 'Stick', 'minecraft:stick', 64, 1, 1, 'Stick : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('281', 'Bowl', 'minecraft:bowl', 16, 1, 1, 'Bowl : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('259', 'Flint and Steel', 'minecraft:flint_and_steel', 1, 1, 0, 'Flint and Steel : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('262', 'Arrow', 'minecraft:arrow', 64, 1, 0, 'Arrow : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('263', 'Coal', 'minecraft:coal', 64, 0, 0, 'Coal : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('263:1', 'Charcoal', 'minecraft:coal', 64, 0, 1, 'Charcoal : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('264', 'Diamond', 'minecraft:diamond', 64, 0, 0, 'Diamond : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('265', 'Iron Ingot', 'minecraft:iron_ingot', 64, 0, 0, 'Iron Ingot : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('266', 'Gold Ingot', 'minecraft:gold_ingot', 64, 0, 0, 'Gold Ingot : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('358', 'Map', 'minecraft:map', 16, 1, 1, 'Map : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('368', 'Ender Pearl', 'minecraft:ender_pearl', 16, 0, 1, 'Ender Pearl : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('369', 'Blaze Rod', 'minecraft:blaze_rod', 64, 0, 1, 'Blaze Rod : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('370', 'Ghast Tear', 'minecraft:ghast_tear', 64, 0, 1, 'Ghast Tear : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('371', 'Gold Nugget', 'minecraft:gold_nugget', 64, 1, 0, 'Gold Nugget : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('372', 'Nether Wart Seeds', 'minecraft:nether_wart', 64, 0, 1, 'Nether Wart Seeds : a useful item in Minecraft with various applications.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('2256', '13 Disk', 'minecraft:music_disc_13', 1, 0, 0, 'A haunting melody echoes from the past, stirring memories long forgotten.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('2257', 'Cat Disk', 'minecraft:music_disc_cat', 1, 0, 0, 'A haunting melody echoes from the past, stirring memories long forgotten.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('2258', 'Blocks Disk', 'minecraft:music_disc_cat', 1, 0, 0, 'A haunting melody echoes from the past, stirring memories long forgotten.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('2259', 'Chirp Disk', 'minecraft:music_disc_chirp', 1, 0, 0, 'A haunting melody echoes from the past, stirring memories long forgotten.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('2260', 'Far Disk', 'minecraft:music_disc_far', 1, 0, 0, 'A haunting melody echoes from the past, stirring memories long forgotten.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('2261', 'Mall Disk', 'minecraft:music_disc_mall', 1, 0, 0, 'A haunting melody echoes from the past, stirring memories long forgotten.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('2262', 'Mellohi Disk', 'minecraft:music_disc_mellohi', 1, 0, 0, 'A haunting melody echoes from the past, stirring memories long forgotten.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('2263', 'Stal Disk', 'minecraft:music_disc_stal', 1, 0, 0, 'A haunting melody echoes from the past, stirring memories long forgotten.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('2264', 'Strad Disk', 'minecraft:music_disc_strad', 1, 0, 0, 'A haunting melody echoes from the past, stirring memories long forgotten.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('2265', 'Ward Disk', 'minecraft:music_disc_ward', 1, 0, 0, 'A haunting melody echoes from the past, stirring memories long forgotten.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('2266', '11 Disk', 'minecraft:music_disc_11', 1, 0, 0, 'A haunting melody echoes from the past, stirring memories long forgotten.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('325', 'Bucket', 'minecraft:bucket', 16, 1, 0, 'A simple bucket', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('327', 'Lava Bucket', 'minecraft:lava_bucket', 1, 0, 0, 'A simple bucket but with lava inside', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('326', 'Water Bucket', 'minecraft:water_bucket', 1, 0, 0, 'A simple bucket but with water inside', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('2267', 'Wait Disc', 'minecraft:music_disc_wait', 1, 0, 0, 'A haunting melody echoes from the past, stirring memories long forgotten.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('336', 'Clay Brick', 'minecraft:brick', 64, 1, 1, 'Smelted from clay, used to craft brick blocks for building.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('338', 'Sugar Cane', 'minecraft:sugar_cane', 64, 0, 1, 'Grows near water, used for paper and sugar production.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('374', 'Glass Bottle', 'minecraft:glass_bottle', 16, 1, 1, 'Used to hold potions, crafted from glass.', 1);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('375', 'Spider Eye', 'minecraft:spider_eye', 64, 0, 1, 'Dropped by spiders, used in brewing awkward potions.', 2);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('376', 'Fermented Spider Eye', 'minecraft:fermented_spider_eye', 64, 1, 1, 'Crafted with spider eye, mushroom, and sugar. Used in brewing.', 2);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('377', 'Blaze Powder', 'minecraft:blaze_powder', 64, 1, 0, 'Made from blaze rods, used in brewing and crafting.', 2);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('378', 'Magma Cream', 'minecraft:magma_cream', 64, 1, 1, 'Used in brewing fire resistance potions. Made from blaze powder and slimeball.', 2);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('381', 'Eye of Ender', 'minecraft:ender_eye', 64, 1, 1, 'Guides to strongholds and activates End Portals.', 3);
INSERT INTO minecraftalpha.items (numID, name, textID, stackSize, craftability, renewability, description, rarityID) VALUES ('382', 'Glistering Melon', 'minecraft:glistering_melon_slice', 64, 1, 1, 'Made from melon and gold nuggets. Used in healing potions.', 2);
